# **CS 725 Project : Classification of Lidar Points using ML Algorithms**

Models tested: 

*   SVM
*   Decision Tree
*   Random Forest
*   Naive Bayes




## Libraries

In [ ]:
import numpy as np
import pandas as pd

# Libraries for different classifiers
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

# Libraries for model evaluation
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## Loading Data

In [ ]:
# Mounting the drive

# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Loading data as a dataframe

#data = pd.read_csv("/content/drive/MyDrive/IIT Bombay/CS 725 Project/lidar_data_classification.csv")
data = pd.read_csv("/Dataset/classification.csv")
data.head()

Unnamed: 0       long         lat  elev  rt_num  class  intensity  \
0           0  83150.336  439662.362   313       1      1        141   
1           1  83150.412  439662.657   -39       1      1        126   
2           2  83150.429  439662.496  -883       2      1         13   
3           3  83150.513  439662.685 -1709       1      2        248   
4           4  83150.298  439660.188 -1690       1      2        447   

   latitude  longtitude  
0  4.342285   51.940770  
1  4.342286   51.940772  
2  4.342286   51.940771  
3  4.342287   51.940773  
4  4.342285   51.940750

In [ ]:
# Selecting features and target from the dataframe

X = data[['elev', 'rt_num', 'intensity', 'latitude', 'longtitude']]
Y = data['class']

In [ ]:
# Splitting test and train

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.9, random_state=42)

## SVM

In [ ]:
# SVM model

model1 = SVC()
model1.fit(x_train, y_train)

SVC()

In [ ]:
# Model testing

model1.score(x_test, y_test)
predictions = model1.predict(x_test)

In [ ]:
# Confusion Matrix

CM_svm=confusion_matrix(y_test, predictions)
print(CM_svm)

[[374985  27220   6247     25]
 [  3666 414142      0    566]
 [ 16814      0  49058      0]
 [     0   1507      0   5770]]


In [ ]:
# Accuracy

acc = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.95      0.92      0.93    408477
           2       0.94      0.99      0.96    418374
           6       0.89      0.74      0.81     65872
           9       0.91      0.79      0.85      7277

    accuracy                           0.94    900000
   macro avg       0.92      0.86      0.89    900000
weighted avg       0.94      0.94      0.94    900000



## Decision Tree

In [ ]:
# Decision Tree model

model2 = DecisionTreeClassifier()
model2.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
# Model testing

model2.score(x_test, y_test)
predictions = model2.predict(x_test)

In [ ]:
# Confusion Matrix

CM_dt=confusion_matrix(y_test, predictions)
print(CM_dt)

[[393545  10069   4837     26]
 [ 10020 407533      0    821]
 [  4716      0  61156      0]
 [    32    632      0   6613]]


In [ ]:
# Accuracy

acc = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.96      0.96      0.96    408477
           2       0.97      0.97      0.97    418374
           6       0.93      0.93      0.93     65872
           9       0.89      0.91      0.90      7277

    accuracy                           0.97    900000
   macro avg       0.94      0.94      0.94    900000
weighted avg       0.97      0.97      0.97    900000



## Random Forest

In [ ]:
# Random Forest model

model3 = RandomForestClassifier()
model3.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
# Model testing

model3.score(x_test, y_test)
predictions = model3.predict(x_test)

In [ ]:
# Confusion Matrix

CM_rf = confusion_matrix(y_test, predictions)
CM_rf

array([[394583,  11644,   2225,     25],
       [  1574, 416118,      0,    682],
       [  3845,      0,  62027,      0],
       [     3,    516,      0,   6758]])

In [ ]:
# Accuracy

acc = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.99      0.97      0.98    408477
           2       0.97      0.99      0.98    418374
           6       0.97      0.94      0.95     65872
           9       0.91      0.93      0.92      7277

    accuracy                           0.98    900000
   macro avg       0.96      0.96      0.96    900000
weighted avg       0.98      0.98      0.98    900000



## Naive Bayes

In [ ]:
# Naive Bayes model

model4 = GaussianNB()
model4.fit(x_train, y_train)

GaussianNB()

In [ ]:
# Model testing

model4.score(x_test, y_test)
predictions = model4.predict(x_test)

In [ ]:
# Confusion Matrix

CM_nb = confusion_matrix(y_test, predictions)
print(CM_nb)

[[279600  33332  95495     50]
 [  3781 413982      0    611]
 [  4460      0  61412      0]
 [   102   2180      0   4995]]


In [ ]:
# Accuracy

acc = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.97      0.68      0.80    408477
           2       0.92      0.99      0.95    418374
           6       0.39      0.93      0.55     65872
           9       0.88      0.69      0.77      7277

    accuracy                           0.84    900000
   macro avg       0.79      0.82      0.77    900000
weighted avg       0.90      0.84      0.85    900000

